force-app/main/default/objects/OLD_SKU__c/OLD_SKU__c.object-meta.xml
<CustomObject>
    <label>OLD  SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OLD SKUS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OLD_SKU__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OLD SKUS</relationshipLabel>
    <relationshipName>OLD_SKUS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesrep_Adj_Price__c/Salesrep_Adj_Price__c.object-meta.xml
<CustomObject>
    <label>Salesrep Adj Price</label>
    <nameField>
        <displayFormat>Invoice-{000000}</displayFormat>
        <label>Salesrep Adjustment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesrep Adj Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesrep_Adj_Price__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salesrep Adj Price</relationshipLabel>
    <relationshipName>Salesrep_Adj_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesrep_Adj_Price__c/fields/Sku__c.field-meta.xml
<CustomField>
    <fullName>Sku__c</fullName>
    <label>Sku</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PricingAppapx.cls
public class PricingAppapx {
    public string customer{set;get;}
	public Salesrep_Adj_Price__c std;
    public list<wrap> oldsuklist{set;get;}
    public list<Wrap> selesrec {get;set;}
    public PricingAppapx(ApexPages.StandardController controller)
    {
        std =(Salesrep_Adj_Price__c) controller.getRecord();
    }
    public list<selectoption> getallcustomer()
    {
       List<SelectOption> Cust= new List<SelectOption>();
        Cust.add( new SelectOption('','--Select--'));
        for( account acc : [select id, name from account order by createdDate DESC] ) {
            Cust.add( new SelectOption(acc.id,acc.name));
        }
          
        return Cust;
    }
    public class Wrap
    {
        public Salesrep_Adj_Price__c acc{set;get;}
        public wrap(Salesrep_Adj_Price__c a) 
       {
         acc = a;  
       }
    }
    
    public void savebtn()
    {
        selesrec = new list<Wrap>();
        list<Salesrep_Adj_Price__c> rec1 = [select name,id,Customer__c,Price__c,Sku__c,Start_Date__c,End_Date__c from Salesrep_Adj_Price__c where Customer__c=:customer ];
    	for( Salesrep_Adj_Price__c a :rec1)
        {
            selesrec.add(new wrap(a));
        }
        oldsuklist = new list<Wrap>();
        list<OLD_SKU__c> oldsku = [select id,name,Customer__c,price__c from OLD_SKU__c where customer__C=:Customer];
        map<string,id > mapforold =  new map<string,id>();
        for(OLD_SKU__c old :oldsku)
        {
            mapforold.put(old.name,old.id);
        }
    }
}