force-app/main/default/objects/FIX_SKU__c/FIX_SKU__c.object-meta.xml
<CustomObject>
    <label>FIX SKU</label>
    <nameField>
        <label>SKU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FIX SKUS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OLD_SKU__c/OLD_SKU__c.object-meta.xml
<CustomObject>
    <label>OLD  SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OLD SKUS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesrep_Adj_Price__c/Salesrep_Adj_Price__c.object-meta.xml
<CustomObject>
    <label>Salesrep Adj Price</label>
    <nameField>
        <displayFormat>Invoice-{000000}</displayFormat>
        <label>Salesrep Adjustment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesrep Adj Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesrep_Adj_Price__c/fields/Sku__c.field-meta.xml
<CustomField>
    <fullName>Sku__c</fullName>
    <label>Sku</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testclassforpricingcustpricesubs.cls
@istest
public class testclassforpricingcustpricesubs {

    static testMethod void runPositiveTestCases()  
    {
        list<Salesrep_Adj_Price__c> sales = new list<Salesrep_Adj_Price__c>();
        for(integer i=0;i<10 ;i++)
        {
            Salesrep_Adj_Price__c salesrep = new Salesrep_Adj_Price__c(sku__c ='10'+i, price__c = 150);
            sales.add(salesrep);
        }
        
        list<OLD_SKU__c> old = new list<OLD_SKU__c>();
        for(integer i=0;i<10 ;i++)
        {
            OLD_SKU__c oldsku = new OLD_SKU__c(name ='12'+i, price__c = 180);
            old.add(oldsku);
        }
        
        list<FIX_SKU__c> fix = new list<FIX_SKU__c>();
        for(integer i=0;i<10 ;i++)
        {
            FIX_SKU__c fixsku = new FIX_SKU__c(name ='115'+i, price__c = 200);
            fix.add(fixsku);
        }
        
        Salesrep_Adj_Price__c a = new Salesrep_Adj_Price__c();
        PricingSubspricesubsapx abc = new PricingSubspricesubsapx();
        abc.nxtbtn();
        abc.Finallistbtn();
    }

}