force-app/main/default/objects/FIX_SKU__c/FIX_SKU__c.object-meta.xml
<CustomObject>
    <label>FIX SKU</label>
    <nameField>
        <label>SKU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FIX SKUS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIX_SKU__c/fields/test__c.field-meta.xml
<CustomField>
    <fullName>test__c</fullName>
    <label>test</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>a1</fullName>
            </value>
            <value>
                <fullName>a2</fullName>
            </value>
            <value>
                <fullName>a3</fullName>
            </value>
            <value>
                <fullName>a4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/justtobetest.cls
public class justtobetest {
    public list<FIX_SKU__c> f{set;get;}
    public string idof;
    public justtobetest()
    {
        idof =ApexPages.currentPage().getParameters().get('id');
         f =new list<FIX_SKU__c>();
        f =[select id,name,test__c, price__c from FIX_SKU__c where id=:idof];
    }
    
    public void go()
    {
      	FIX_SKU__c  fx = new FIX_SKU__c();
        fx.Name = f[0].name;
        fx.test__c = f[0].test__c;
        fx.price__c = f[0].price__c;
        fx.Id = idof;
        update fx;
    }

}