force-app/main/default/objects/Rest_Record__c/Rest_Record__c.object-meta.xml
<CustomObject>
    <label>Rest Record</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rest Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rest_Record__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/webservicewithxml.cls
global class webservicewithxml {
    global void restweb()
    {
        Http htp = new http();
        httprequest req = new httprequest();
        req.setEndpoint('http://school.edusuiteondemand.us/PMS_Webservice.asmx/PMS_GETCustomerExcel');
        req.setMethod('GET');
        req.setTimeout(120000);
        HttpResponse res = htp.send(req);
        dom.Document doc = res.getbodydocument();
        dom.XmlNode root =doc.getrootelement();
        list<Rest_Record__c> restobj =new list<Rest_Record__c>(); 
        for(dom.XmlNode abc:root.getChildElements())
        {
            string customername = abc.getChildElement('AccountName',null).getText();
            string CustomerNumber = abc.getChildElement('AccountNumber',null).getText();
            string address = abc.getChildElement('Address',null).getText();
            string phone = abc.getChildElement('Phone',null).getText();
            restobj.add(new Rest_Record__c(name = customername,Customer_Number__c = decimal.valueof(customerNumber),Address__c =Address,Phone__c =Phone));
            
        }
        insert restobj;
        
        
    }

}