force-app/main/default/objects/Rest_Record__c/Rest_Record__c.object-meta.xml
<CustomObject>
    <label>Rest Record</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rest Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rest_Record__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <label>Customer Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/restclloutxmlwithschedule.cls
global class restclloutxmlwithschedule  implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public list<Rest_Record__c> start(database.BatchableContext Bc)
    {
        http htp = new http();
        HttpRequest Req = new HttpRequest();
        req.setEndpoint('http://school.edusuiteondemand.us/PMS_Webservice.asmx/PMS_GETCustomerExcel');
        req.setMethod('GET');
        req.setTimeout(120000);
        HttpResponse res = htp.send(Req);
		dom.Document doc = res.getbodyDocument();
        dom.XmlNode Root = doc.getRootElement();
        list<Rest_Record__c> mer = new list<Rest_Record__c>(); 
        for(dom.XmlNode subchild : root.getChildElements())
        {
            string customername = subchild.getChildElement('AccountName',null).getText();
            Decimal CustomerNumber = Decimal.valueOf(subchild.getChildElement('AccountNumber',null).getText());
            string Address = subchild.getChildElement('Address',null).getText();
            string Phoneno = (subchild.getChildElement('Phone', null).getText());
            mer.add(new Rest_Record__c(name = customername,Customer_Number__c = CustomerNumber,Address__c =Address,Phone__c =Phoneno));
        }
        return mer;
    }
	public void execute(database.BatchableContext Bc,List<Rest_Record__c> scope )
    {
        insert scope;
        system.debug('hello');
    }
    public void finish(Database.BatchableContext BC)
    {
        
    }
    
    
}