force-app/main/default/objects/LineItem__c/LineItem__c.object-meta.xml
<CustomObject>
    <label>LineItem</label>
    <nameField>
        <label>LineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LineItem__c/fields/Merchendise__c.field-meta.xml
<CustomField>
    <fullName>Merchendise__c</fullName>
    <label>Merchandise</label>
    <referenceTo>Merchandise__c</referenceTo>
    <relationshipLabel>LineItems</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/Merchandise__c.object-meta.xml
<CustomObject>
    <label>Merchandise Details</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/checkchildobjectapx.cls
public class checkchildobjectapx {
    public list<Merchandise__c> mer;
    
    public void go()
    {
        mer =new list<Merchandise__c>();
        system.debug('hello ====>>>'+SObjectType.Merchandise__c.getChildRelationships());
        Map<Id, List<SObject>> m = new Map<Id, List<SObject>>();
        for(Merchandise__c merch :[select id,(select id from LineItems__r) from Merchandise__c])
        {
            m.put(merch.Id, merch.LineItems__r);
        }
        system.debug('account  '+m);
    }
        
}